"""Add time column to event

Revision ID: 251453ff772a
Revises: 
Create Date: 2025-12-14 00:42:07.467273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251453ff772a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
